spring:
  application:
    name: book-service
  sleuth:
    sampler:
      probability: 2.0
  zipkin:
    enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: books
  cloud:
    config:
      enabled: false
server:
  port: 8877
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # 1 укажите явный маршрут к серверу eureka (serviceUrl)
    eureka-service-url-poll-interval-seconds: 35 # 3 укажите интервал в 35 сек через который клиент шлет эхо запрос на сервер
  instance:
    preferIpAddress: true # 2 использовать IP адрес
